### ISSUE TITLE
release config on keep best part

### ISSUE THREAD

**Issue by bravocado** [PokemonGoF/botConfig#2]
https://github.com/PokemonGoF/botConfig/blob/gh-pages/views/partials/tabs/release_table.html#L46-L53

Should be select maybe. Since the option just "true" or "false". yeah user can use "1" or "0". But, you know the purpose of this config generator to make it easier. :)

**Comment by brantje** [comment]
With a number it keeps the x strongest iv  / cp. Tested this and it worked.
