### ISSUE TITLE
Config page design

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/botConfig#7]
Will it be easier to set parameters if the page is designed like this. No functions are changed, just add `<div>` in `<td>`

![image 1](https://cloud.githubusercontent.com/assets/5256572/17346926/f5b96e6a-5904-11e6-8263-3d2a34add219.png)

**Comment by brantje** [comment]
Great idea! Will look into it, the data-bindings still need to work.

**Comment by brantje** [comment]
Added in master branch, not yet pushed to gh-pages.
